import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum CommunicationProtocol {
  @JsonValue('command')
  command,

  @JsonValue('requestResponse')
  requestResponse,

  @JsonValue('message')
  message,

  @JsonValue('collaboration')
  collaboration,

  @JsonValue('longRunningTask')
  longRunningTask
}

// Add this extension to handle serialization
extension CommunicationProtocolExtension on CommunicationProtocol {
  String toJson() => _$CommunicationProtocolEnumMap[this]!;
}

// This map will be generated by json_serializable
// We declare it here to avoid lint warnings
const _$CommunicationProtocolEnumMap = {
  CommunicationProtocol.command: 'command',
  CommunicationProtocol.requestResponse: 'requestResponse',
  CommunicationProtocol.message: 'message',
  CommunicationProtocol.collaboration: 'collaboration',
  CommunicationProtocol.longRunningTask: 'longRunningTask',
};